### ISSUE TITLE
Nuevos movimientos en cuenta

### ISSUE THREAD

**Issue by VictorDegano** [VictorDegano/desapp-groupA-2019S1#13]
En la cuenta cuando se genera un nuevo movimiento(Deposit, extract o addDebt) estaria bueno que la misma clase Moviment genere el movimiento. 
EJ: 
En vez de hacer 
`new Movement(amount,MovementType.DEBT,LocalDateTime.now())` 
creo que quedaria mejor patear esa responsabilidad a la clase Movement y hacer algo como:
`Movement.Debt(Amount)`
Y que eso ya te retorne un nuevo movimiento.

**Comment by Dominikowivan** [comment]
Super de acuerdo!

**Comment by Dominikowivan** [comment]
arreglado!
