### ISSUE TITLE
DebtMovements

### ISSUE THREAD

**Issue by VictorDegano** [VictorDegano/desapp-groupA-2019S1#14]
Creo que queda mas legible `movement.isDebt()` o  `movement.isMovementType(movementType.DEBT)` que `movement.getType().equals(MovementType.DEBT)`. Me parece eso una responsabilidad mas del movimiento que de la cuenta.

**Comment by Dominikowivan** [comment]
De acuerdo!

**Comment by Dominikowivan** [comment]
Arreglado!
