### ISSUE TITLE
Abstraer el test de la construccion de objetos

### ISSUE THREAD

**Issue by Dominikowivan** [VictorDegano/desapp-groupA-2019S1#2]
En FiestaTest:
En whenAGuestConfirmTheAssistance_TheQuantityOfConfirmationsChangeAndTheGuestHaveYourConfirmationInTrue:

Es mas fácil de leer el test si nos abstraemos de que se hace para construir los colaboradores.

Propongo que en vez de que este así:
```java
User userToAssist = randomUserWithName("Ivan");

Guest firstGuest = GuestBuilder.buildAGuest()
                                       .withUser(userToAssist)
                                       .build();

Fiesta fiestaSUT = FiestaBuilder.buildAFiesta()
                                        .addGuest(firstGuest)
                                        .withConfirmations(0)
                                        .build();
```

Dejarlo así:

```java
Guest  guest =  randomGuest();
Fiesta fiestaSut= fiestaWithGuest(guest);
```

**Comment by VictorDegano** [comment]
Cuando sea tiempo de refactorizar los test se vera un comportamiento en común y se lo extraerá en métodos auxiliares. Fuera de eso es el contexto de prueba, si modificas alguno de esos valores falla el test no es bueno extraer los datos o cosas que pretende validar el test en métodos sin poder modificar en el test. 
En todo caso el refactor correcto seria un método que cree el contexto para ese test que reciba el nombre del invitado y la cantidad de confirmaciones.

**Comment by Dominikowivan** [comment]
No me parece que pase por el lado de refactorizar comportamiento en comun, mi observacion es que para el que lee el test, la preocupacion de como se construyen los objetos que utiliza el mismo test como colaboradores, son detalles de implementacion. Si yo soy tecnico y quiero ver los detalles de implementacion, me meto y los veo.

Propongo el siguiente aproximamiento que podemos discutir bien:
Escribir los test del negocio (hago incapie sobretodo para el negocio) tal manera que se lean como una narracion que una persona no tecnica pueda validar el comportamiento esperado.

Te abstraes de que herramientas tecnologias usas para resolver el problema, y eso te permite cambiarlas en el futuro.
