### ISSUE TITLE
Estado

### ISSUE THREAD

**Issue by Dominikowivan** [VictorDegano/desapp-groupA-2019S1#22]
En Goods:
que necesidad hay de que las propiedades del good no sean finales??
Si yo tengo una función que itera sobre los goods, digamos, para calcular un precio
que garantía tengo de que durante mi iteracion alguien no cambio el precio de uno de los goods mientras recorría y calculaba?

Cuando introducimos estado, toda garantía se tira por la ventana. Tengo que concientemente estar pendiente del contexto de que en ningún otro lado puede darse la situación en la cual alguien me va a tocar el objeto mientras lo estoy usando y, por ahí cuando el projecto arranca es fácil... Pero después de 6 meses de desarrollo (por no decir años)... después de que todo el equipo cambio 3 veces(por no decir 10)... es un poco difícil.

Cuando es fácil evitar el estado, evitemoslo.

Lo mismo en template, un template con cualquier parámetro diferente es otra entidad completamente.

**Comment by VictorDegano** [comment]
Que sea final quiere decir que una vez inicializado el objeto el valor que posee ya no es modificable, esto haría que hibernate no pueda instanciar al good a traves de su constructor vació y asignarle el precio devuelto. 

Si se esta seguro que va a ser un objecto que va a vivir en el modelo y no en las demás capaz no hay problema con que sea final, en este caso no.

**Comment by Dominikowivan** [comment]
Se puede. Es mas! En hibernate no solo tenes entidades (que las caracterizas con el mappeo de @Entity), Tambien tenes Value objects!!! (Los caracterizas con @Embedded). 

Si hace falta ejemplo de como hacerlo despues lo preparo y lo vemos, pero no pensemos en concerns de persistencia cuando modelamos nuestro dominio.
