### ISSUE TITLE
Baja cohesion en Goods

### ISSUE THREAD

**Issue by Dominikowivan** [VictorDegano/desapp-groupA-2019S1#23]
Un "bien" puede ser el salon.
tiene sentido entonces que el bien tenga un "cantidad por persona?"

Canasta y Baquita no usan para nada ese parametro del good.
Se esta bajando la cohesion dejándolo ahí.

Propongo dos soluciones:
Que la fiesta lleve un map que dado un bien te devuelve una cantidad.
Crear un fiestaGood que herede de Good y guardar una lista de eso.

**Comment by VictorDegano** [comment]
El good fue creado en conjunto con la fiesta por lo que fue diseñado acorde a esta. Cuando se haga la refactorizacion de código de seguro aparecerán distintos tipos de goods o un good para cada tipo de evento.

No hay que dar pasos mas grandes de lo que uno puede dar, o debe dar. Sobre dimensionar una solucion desde el inicio a veces es tan malo como un objeto con comportamiento de mas.

**Comment by Dominikowivan** [comment]
Concuerdo!

Pero hay un concern que gana mas prioridad, que es que deberiamos desde el vamos partir con una estructura que es valida para toda concrecion de las entidades que queremos representar (dentro del contexto que se nos dio).

Propongo que partamos siempre de estructuras que son validas siempre, y si necesitan algo mas nos preguntemos "si le agrego esto, sigue siendo una representacion valida?".

Lo mismo con el tema de la cohesion. Cada vez que agreguemos un colaborador preguntemosnos: Le interesa ese colaborador a todos los objetos que dependen de el?

**Comment by VictorDegano** [comment]
Esa preguntas que haces son las que hay que hacerse en momentos que vez varias entidades haciendo la misma logica (o parecida) y es el momento de separar responsabilidad (Componiendo o heredando), en especial la segunda pregunta. 

A menos, claro, que tengas que crear una entidad que desde el inicio tenes que hacerla para varios tipos de entidades, ahi si esas preguntas caen desde el inicio. Sino, es mejor ir paso a paso: Crear, testear, refactorizar, volver a crear.

Esas preguntas son buenas, pero son much mas utiles si son hechas cuando se esta definidas las colaboraciones. En nuestro caso el modelo esta en pleno desarrollo y, para mi, son mucho mas utiles en los refactors donde de seguro van a salir entidades mas generales.

**Comment by Dominikowivan** [comment]
De acuerdo con eso! pero una cosa no quita la otra.
 "si le agrego esto, sigue siendo una representación valida?".
"Le interesa ese colaborador a todos los objetos que dependen de el?"
son Preguntas que se pueden hacer al modificar un objeto independientemente del estado de la aplicación. Nueva vieja, son preguntas validas. Después cuando va avanzándose agregan las preguntas de "No hará falta sacar esto a otro lado?" pero las otras dos vienen antes.
