### ISSUE TITLE
Información de mas en FiestaTest

### ISSUE THREAD

**Issue by Dominikowivan** [VictorDegano/desapp-groupA-2019S1#24]
En FiestaTest
En whenAGuestConfirmTheAsistance_TheQuantityOfGoodsAreRecalculated

Tengo que saber el nombre de los goods? Tengo que saber la cantidad por persona?
Si son irrelevantes al comportamiento testeado en el test, se pueden obviar.

En vez de esto:
```java
User userToAssist = UserBuilder.buildAUser()
                                       .withFirstName("Ivan")
                                       .build();

        Guest firstGuest = GuestBuilder.buildAGuest()
                                       .withUser(userToAssist)
                                       .build();

        Good beer = GoodBuilder.buildAGood()
                               .withName("Beer")
                               .withQuantityForPerson(2)
                               .build();

        Good doritoPack  = GoodBuilder.buildAGood()
                                      .withName("Dorito")
                                      .withQuantityForPerson(1)
                                      .build();

        Fiesta fiestaSUT = FiestaBuilder.buildAFiesta()
                                        .addGood(beer)
                                        .addGood(doritoPack)
                                        .addGuest(firstGuest)
                                        .withConfirmations(0)
                                        .build();
    //Exercise(When)
        fiestaSUT.completeConfirmationAsistance(firstGuest);
```
Propongo:
```java
   Guest guest       = randomGuest();
   Fiesta fiestaSUT = FiestaBuilder.buildAFiesta()
                                        .addGood(randomGood())
                                        .addGood(randomGood())
                                        .addGuest(guest)
                                        .withConfirmations(0)
                                        .build();
    //Exercise(When)
        fiestaSUT.completeConfirmationAsistance(guest);
```

**Comment by VictorDegano** [comment]
En el caso del nombre del good no es necesario el nombre en ese test, se lo saca tranquilamente. Igual el uso de datos random no es recomendable, en especial si randomizas un dato que queres testear (Por eso esta el builder).
 
La cantidad por persona si se tiene que saber, por que se testea justamente que cuando se confirme una asistencia la cantidad final de los Goods sea recalculado correctamente y para eso tiene que haber una cantidad por persona.

**Comment by Dominikowivan** [comment]
>uso de datos random no es recomendable.

 Si es un dato que queres testear, seguro, pero de otra forma, si tiene que funcionar con cualquier dato y funciona, estas añadiendo resilencia.

Mi punto es que varios de los datos no son de interes para la persona que lee el test, entonces es mejor obviarlos, y que te quede algo muchisimo mas chico y facil de leer. 

Para nosotros ahora es facil entender cual es el contexto y que se necesita, por que el proyecto es chico y lo estamos arrancando de 0. Pero Jayce el Ingles que va a entrar de aca a 2 años cuando el proyecto crezca, va a tener que leer con detenimiento y perder tiempo entendiendo que la persona era accidental a lo que se quiere testear.

**Comment by VictorDegano** [comment]
Si en eso si estoy de acuerdo con vos, entre menos codigo distractivo haya mejor.

**Comment by Dominikowivan** [comment]
Grande Victor! Problema adresseado.
