### ISSUE TITLE
Sobredocumentacion

### ISSUE THREAD

**Issue by Dominikowivan** [VictorDegano/desapp-groupA-2019S1#4]
En Fiesta
En confiarmAsistanceOf

Hay que tener criterio para cuando decidimos documentar con comentarios. 
Los comentarios dependen del método enormemente, y no es raro que cuando cambia el método, tenga que cambiar el comentario.
Lo ideal es que uno cambie el método, y cambie el comentario, pero la realidad es que rara vez hay tiempo para eso, y es muy consumidor mantener los comentarios actualizados.

La regla de dedo es que  cundo trabajas en tu modelo, el código tiene que ser tu documentación, tiene que narrar la lógica de lo que sucede el mismo. Si no podes leer el código de tu modelo como si fuera una narración, algo esta saliendo mal y hay que repensarlo.

Guardemos los comentarios para detalles de implementacion de Herramientas de programación que puedan parecer esotericas o complicadas.

**Comment by VictorDegano** [comment]
Eso es discutible, en este caso el método es chico y puede sobrar el javaDoc. Pero también hay que tener en cuenta que a medida que una implementacion crece también lo que se debe documentar. Si un método o clase es muy compleja o grande y no la documenta el mismo que la desarrollo en su momento, el que tenga que modificarlo va tardar mas en entenderlo que en arreglarlo.

Hay que programar pensando en que el siguiente que lo vaya a tocar no sos vos, sos vos dentro de mucho tiempo o alguien que no esta tan ducho como vos en el modelo.

**Comment by Dominikowivan** [comment]
100% de acuerdo con que es discutible.

Si una clase es muy compleja o grande, es indicio que falta segregar responsabilidades. 

Propongo el siguiente acuerdo de gentilhombres:
Todo metodo y clase del modelo tiene que ser lo suficientemente pequeño y consiso como para que se entienda rapidamente que es y que hace sin necesidad que te lo expliquen.
SI aparece la necesidad de documentar, considera segregar el problema de tal manera que se lea lo que esta pasando como si fuera una narracion.
